export type IGravestoneItem = {
  id?: string;
  graveyardId: string;
  name: string;
  firstName: string;
  lastName: string;
  birthday: string;
  deceasedDate: string;
  buriedDate: string;
  quarter: string;
  graveSite: string;
  homeTown: string;
  graveSiteNumber: string;
  ageOnDeath?: string;
  churchNumber?: string;
  field?: string;
  row?: string;
  place?: string;
  graveyardDetails?: any;
  burriedWith?: string;
  approved?: boolean;
  createdAt?: Date;
  updateAt?: Date;
  bio?: string;
};
